using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using AzureFunctions.Extensions.Swashbuckle;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.OpenApi;
using Microsoft.OpenApi.Any;
using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;
using TestFunction;

[assembly: WebJobsStartup(typeof(SwashBuckleStartup))]
namespace TestFunction
{
    
    internal class SwashBuckleStartup : IWebJobsStartup
    {
        public void Configure(IWebJobsBuilder builder)
        {
            //Register the extension
            builder.AddSwashBuckle(Assembly.GetExecutingAssembly(), opts =>
            {
                opts.OpenApiSpec = OpenApiSpecVersion.OpenApi3_0;
                opts.Documents = new OptionDocument[]
                {
                    new OptionDocument { Description = "Custom Generated By Swashbuckle", Name = "v1", Title = "Test API", Version = "v1.1.10"}, 
                };
                opts.Title = "Hello";
                opts.FillSwaggerBasePathWithRoutePrefix = false;
                opts.SwaggerConfigurator = s =>
                {
                    s.SchemaFilter<TestController.TypeExcludeFilter>(new TestController.TypeExcludeFilter.Options(typeof(IModelValidator)));
                };
            });

        }
    }
}
